// This header file was auto-generated by ClassMate++
// Created: 28 Feb 2018 8:30:14 am
// Copyright (c) 2018, HurleyWorks

#pragma once

class Minimal
{
 public:
    Minimal();
    ~Minimal();

    void tick (size_t frameNumber);

 private:
}; // end class Minimal
