// This source file was auto-generated by ClassMate++
// Created: 28 Feb 2018 8:30:14 am
// Copyright (c) 2018, HurleyWorks

#include "Minimal.h"

// ctor
Minimal::Minimal()
{
    
}

// dtor
Minimal::~Minimal()
{
   
}

// tick
void Minimal::tick (size_t frameNumber)
{
    std::cout << frameNumber << std::endl;
}
